name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile A4
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Jugendteam_Spielesammlung_A4.tex
          working_directory: ./A4
          args: -pdf -file-line-error -interaction=nonstopmode
        continue-on-error: true
      - name: Upload A4 PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: A4/Jugendteam_Spielesammlung_A4.pdf
        continue-on-error: true

